[window]

decorations = "Buttonless"
dynamic_padding = true
padding = { x = 5, y = 5}
decorations_theme_variant = "Dark"
opacity = 0.8
blur = false 

[bell]

animation = "Linear"
duration = 50
color = "#698DDA" # same as tmux

[cursor] 

style = { shape = "Beam", blinking = "Always" }

[terminal] 

osc52 = "CopyPaste"

[font]

size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
builtin_box_drawing = false
